"""
This type stub file was generated by pyright.
"""

import sys

if sys.version_info[0] == 2:
    ...
else:
    string_types = ...
if list(sys.version_info[: 2]) >= [2, 7]:
    ...
else:
    ...
class UnicodeMixin:
    """
    Mixin that defines proper __str__/__unicode__ methods in Python 2 or 3.
    """
    if sys.version_info[0] >= 3:
        def __str__(self) -> str:
            ...
        
    else:
        ...


